export { useCasino } from './useCasino'
export { useMultiRoomPrediction } from './useMultiRoomPrediction'
export { useRoomFilters } from './useRoomFilters'
export { useVirtualBetting } from './useVirtualBetting'
export { useAutoMode } from './useAutoMode'
export { useSession } from './useSession'
export { useGameEvents } from './useGameEvents'
export { useWindowControl } from './useWindowControl'
export { useCustomPatterns } from './useCustomPatterns'
export { useHistoryLog } from './useHistoryLog'

// Re-export from context for convenience
export { useError } from '../context'

export type { UseCasinoResult, ConnectionStatus, CasinoProvider } from './useCasino'
export type { UseMultiRoomPredictionResult } from './useMultiRoomPrediction'
export type { UseRoomFiltersResult } from './useRoomFilters'
export type { UseVirtualBettingResult } from './useVirtualBetting'
export type { UseAutoModeResult } from './useAutoMode'
export type { LogEntry, ResultOverlayData } from './useGameEvents'
export type { CustomPatternInput } from './useCustomPatterns'
export type { BaseHistoryLog, SemiAutoHistoryLog, AutoModeHistoryLog } from './useHistoryLog'
